### ISSUE TITLE
IllegalArgumentException with minifyEnabled true 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-events-android#310] opened 2018-12-03 20:37 UTC
Found in the release build (`minifyEnabled true`) of the navigation test app:
```
12-03 13:03:59.304 23951-23951/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.testapp, PID: 23951
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.mapbox.scheduler_flusher flg=0x14 (has extras) } in com.mapbox.android.telemetry.a@737eb10
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1412)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Invalid attempt to bind an instance of com.mapbox.android.telemetry.br as a @JsonAdapter for com.mapbox.android.telemetry.bl. @JsonAdapter value must be a TypeAdapter, TypeAdapterFactory, JsonSerializer or JsonDeserializer.
        at com.google.gson.b.a.d.a(Unknown Source:87)
        at com.google.gson.b.a.i.a(Unknown Source:27)
        at com.google.gson.b.a.i.a(Unknown Source:123)
        at com.google.gson.b.a.i.create(Unknown Source:22)
        at com.google.gson.f.a(Unknown Source:74)
        at com.google.gson.f.a(Unknown Source:4)
        at com.google.gson.f.a(Unknown Source:5)
        at com.google.gson.f.a(Unknown Source:9)
        at com.google.gson.b.a.l$a.a(Unknown Source:4)
        at com.mapbox.android.telemetry.bu.b(Unknown Source:4)
        at com.mapbox.android.telemetry.bu.a(Unknown Source:17)
        at com.mapbox.android.telemetry.bu.serialize(Unknown Source:2)
        at com.google.gson.b.a.l.write(Unknown Source:28)
        at com.google.gson.b.a.m.write(Unknown Source:35)
        at com.google.gson.b.a.b$a.a(Unknown Source:25)
        at com.google.gson.b.a.b$a.write(Unknown Source:2)
        at com.google.gson.f.a(Unknown Source:34)
        at com.google.gson.f.a(Unknown Source:8)
        at com.google.gson.f.b(Unknown Source:5)
        at com.google.gson.f.b(Unknown Source:13)
        at com.mapbox.android.telemetry.cf.b(Unknown Source:8)
        at com.mapbox.android.telemetry.cf.a(Unknown Source:8)
        at com.mapbox.android.telemetry.MapboxTelemetry.c(Unknown Source:14)
        at com.mapbox.android.telemetry.MapboxTelemetry.b(Unknown Source:6)
        at com.mapbox.android.telemetry.MapboxTelemetry.m(Unknown Source:17)
        at com.mapbox.android.telemetry.MapboxTelemetry.a(Unknown Source:0)
        at com.mapbox.android.telemetry.MapboxTelemetry$1.a(Unknown Source:2)
        at com.mapbox.android.telemetry.a.onReceive(Unknown Source:14)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:280) 
        at android.app.ActivityThread.main(ActivityThread.java:6710) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

Added this rule as a quick fix, resolving the crashes:
```
-keep class com.mapbox.android.telemetry.** { *; }
```

**Comment by Chaoba** [comment] 2019-05-16 02:25
This issue is caused by Gson serialize. It should be fixed after this [PR](https://github.com/mapbox/mapbox-navigation-android/pull/1890) is merged, because we removed all sub classes of `JsonSerializer`

**Comment by andrlee** [comment] 2019-05-16 15:51
thanks @Chaoba closing

**Closed by andrlee** 2019-05-16 15:51 UTC
Labels: bug, high priority
