### ISSUE TITLE
Migrate TelemetryService to using getApplicationContext()

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#263] opened 2018-10-29 16:07 UTC
Address this work: https://github.com/mapbox/mapbox-events-android/issues/146#issuecomment-433968009

To prevent possible instances where `MapboxTelemetry.applicationContext` is null due to differing lifecycles, we will migrate from using this static context within our `TelemetryService` to using `getApplicationContext()`. This will prevent odd crashes we are noticing in over-managed OS's and under odd corner cases, where context is not set, but processes are running.

- [x] remove all reference to `MapboxTelemetry.applicationContext` from `TelemetryService`
- [x] replace with `getApplicationContext()`
- [x] remove context check method
- [x] add tests to confirm working fix

**Comment by andrlee** [comment] 2018-10-29 17:01
@electrostat i think the problem might be bigger than just invalid context ref, we need to get to the root cause: i.e. why context is null in a first place. You might need to instrument `TelemetryService` to get to that.

**Comment by andrlee** [comment] 2018-11-01 06:31
Fixed with https://github.com/mapbox/mapbox-events-android/pull/265

**Closed by andrlee** 2018-11-01 06:31 UTC
Labels: bug
