### ISSUE TITLE
Strict mode violation

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-events-android#198] opened 2018-08-16 13:45 UTC
Refs https://github.com/mapbox/mapbox-events-android/issues/140.

Telemetry is violating the strict mode:
```
08-16 15:32:43.962 6672-6672/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=109 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.getDataDir(ContextImpl.java:2253)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:550)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:747)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:400)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainSharedPreferences(TelemetryUtils.java:191)
        at com.mapbox.android.telemetry.TelemetryLocationEnabler.updateLocationPreferences(TelemetryLocationEnabler.java:61)
        at com.mapbox.android.telemetry.TelemetryLocationEnabler.updateTelemetryLocationState(TelemetryLocationEnabler.java:40)
        at com.mapbox.android.telemetry.MapboxTelemetry.initializeTelemetryLocationState(MapboxTelemetry.java:404)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:77)
        at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:21)
        at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:10)
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.<clinit>(Telemetry.java:69)
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:68)
        at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:73)
        at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:124)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.initializeMapbox(MapboxApplication.java:72)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:36)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by tobrun** [comment] 2019-02-22 10:07
bump on this, not only still an issue, it's logging even more strictmode warnings:

```
2019-02-22 11:05:57.402 24291-24291/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=33 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:807)
        at android.app.ContextImpl.getDataDir(ContextImpl.java:2197)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:517)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:714)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:368)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainSharedPreferences(TelemetryUtils.java:187)
        at com.mapbox.android.telemetry.ConfigurationClient.shouldUpdate(ConfigurationClient.java:60)
        at com.mapbox.android.telemetry.CertificateBlacklist.<init>(CertificateBlacklist.java:38)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:64)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:31)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:129)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.initializeMapbox(MapboxApplication.java:77)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-02-22 11:05:57.402 24291-24291/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=31 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:807)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:572)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:563)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:519)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:714)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:368)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainSharedPreferences(TelemetryUtils.java:187)
        at com.mapbox.android.telemetry.ConfigurationClient.shouldUpdate(ConfigurationClient.java:60)
        at com.mapbox.android.telemetry.CertificateBlacklist.<init>(CertificateBlacklist.java:38)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:64)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:31)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:129)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.initializeMapbox(MapboxApplication.java:77)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-02-22 11:05:57.402 24291-24291/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=29 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:234)
        at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:279)
        at com.mapbox.android.telemetry.ConfigurationClient.shouldUpdate(ConfigurationClient.java:61)
        at com.mapbox.android.telemetry.CertificateBlacklist.<init>(CertificateBlacklist.java:38)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:64)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:31)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:129)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.initializeMapbox(MapboxApplication.java:77)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-02-22 11:05:57.402 24291-24291/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=26 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:807)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:572)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:563)
        at android.app.ContextImpl.getFilesDir(ContextImpl.java:608)
        at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:232)
        at com.mapbox.android.telemetry.CertificateBlacklist.<init>(CertificateBlacklist.java:41)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:64)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:31)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:129)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.initializeMapbox(MapboxApplication.java:77)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-02-22 11:05:57.403 24291-24291/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=25 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:837)
        at com.mapbox.android.telemetry.CertificateBlacklist.retrieveBlackList(CertificateBlacklist.java:50)
        at com.mapbox.android.telemetry.CertificateBlacklist.<init>(CertificateBlacklist.java:41)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:64)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:31)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:129)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.initializeMapbox(MapboxApplication.java:77)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-02-22 11:05:57.403 24291-24291/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=25 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:807)
        at com.mapbox.android.telemetry.CertificateBlacklist.retrieveBlackList(CertificateBlacklist.java:55)
        at com.mapbox.android.telemetry.CertificateBlacklist.<init>(CertificateBlacklist.java:41)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:64)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:31)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:129)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.initializeMapbox(MapboxApplication.java:77)
        at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

cc @andrlee @electrostat

**Comment by andrlee** [comment] 2019-02-22 14:53
Thanks for bump @tobrun will take a look!

**Comment by Chaoba** [comment] 2019-02-26 07:37
@andrlee It seems that strictmode warnings are caused by this [method](https://github.com/mapbox/mapbox-events-android/blob/6a49d61008d4aac0fc0af55efea9502b364bbd55/libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java#L187) 

To resolve this issue
1. Create a callback interface
2. Add a parameter for `obtainSharedPreferences` method with this callback
3. Create an `AsnycTask` inside `obtainSharedPreferences` to handle `getSharedPreferences`
4. Modify every places that call `obtainSharedPreferences` , maybe need add some other callbacks.

But this solution changes to much code, I don't think it's a good solution. Do you have any ideas on it?

**Comment by andrlee** [comment] 2019-03-08 06:37
These violations have been fixed with https://github.com/mapbox/mapbox-events-android/pull/351 and https://github.com/mapbox/mapbox-events-android/pull/349. This PR adds enhancements to the internal test app and `StrictMode` so hopefully catch these pre-release.

**Closed by andrlee** 2019-03-08 06:37 UTC
Labels: enhancement, medium priority, performace
