### ISSUE TITLE
NullPointerException in TelemetryUtils.obtainApplicationState()

### ISSUE THREAD

**Issue by MariusBoepple** [mapbox/mapbox-events-android#170] opened 2018-07-02 14:06 UTC
**Platform:** Android 7 and 8
**Mapbox SDK version:** `6.1.0`

We have quite a few of the following crash reports:

### Stacktrace

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at com.mapbox.android.telemetry.TelemetryUtils.obtainApplicationState(TelemetryUtils.java:100)
        at com.mapbox.android.telemetry.LocationEvent.<init>(LocationEvent.java:44)
        at com.mapbox.android.telemetry.LocationMapper.createLocationEvent(LocationMapper.java:32)
        at com.mapbox.android.telemetry.LocationMapper.from(LocationMapper.java:18)
        at com.mapbox.android.telemetry.LocationReceiver.sendEvent(LocationReceiver.java:47)
        at com.mapbox.android.telemetry.LocationReceiver.onReceive(LocationReceiver.java:26)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6111)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by electrostat** [comment] 2018-07-03 21:16
@MariusBoepple this is a bug that was addressed in the `3.1.1` version of the telemetry library. That was included in our Maps SDK `6.1.2` and higher. I would bump up to at least 6.1.2 or even the latest release of `6.2.1`. That should handle your issue.

**Closed by electrostat** 2018-07-03 21:16 UTC

**Comment by andrlee** [comment] 2018-11-27 16:31
@chancyWu this comment: 

> @MariusBoepple this is a bug that was addressed in the 3.1.1 version of the telemetry library. That was included in our Maps SDK 6.1.2 and higher. I would bump up to at least 6.1.2 or even the latest release of 6.2.1. That should handle your issue.

is a bit misleading, the root cause of the issue was fixed recently can you please try maps sdk 6.7.1 with mapbox-android-telemtry-3.5.4 and let me know if you still experience this same problem?
