### ISSUE TITLE
🐞 Random crash when app was in the background

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-events-android#458] opened 2020-02-26 13:01 UTC
**Configuration**
 - SDK Version
 implementation ("com.mapbox.navigation:core:1.0.0-20200226.084214-62") {
 implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation:0.43.0-20200224.110749")
 - Android OS Version 10
 - Device model(s): Google Pixel 4 XL
 - App: Mapbox Test App

**Steps to Reproduce**
Hard to reproduce and doesn't always happen

**Expected**
What did you expect?

**Logging**

```
2020-02-26 13:16:45.569 1357-1415/? E/ActivityManager: ANR 
    PID: 13211
    Reason: Broadcast of Intent { act=com.mapbox.android.telemetry.location.locationupdatespendingintent.action.LOCATION_UPDATED flg=0x10 (has extras) }
    Load: 6.5 / 5.65 / 4.87
    CPU usage from 0ms to 6801ms later (2020-02-26 13:16:38.701 to 2020-02-26 13:16:45.502):
      119% 13211/com.mapbox.logistics_example: 111% user + 8.3% kernel / faults: 2653 minor 118 major
      15% 1357/system_server: 7.7% user + 7.7% kernel / faults: 4892 minor 96 major
      15% 624/surfaceflinger: 8.8% user + 6.6% kernel / faults: 599 minor 2 major
      13% 22974/com.pandora.android: 8.3% user + 5.2% kernel / faults: 2778 minor 77 major
      10% 626/android.hardware.graphics.composer@2.3-service-sm8150: 6.7% user + 3.9% kernel
      10% 1033/media.swcodec: 7.2% user + 3% kernel / faults: 9130 minor 25 major
      7.5% 1980/com.google.pixel.livewallpaper:earth: 5.4% user + 2% kernel / faults: 1077 minor 46 major
      5.7% 284/crtc_commit:127: 0% user + 5.7% kernel
      5% 1889/com.android.systemui: 3% user + 1.9% kernel / faults: 2423 minor 109 major
      3.9% 3491/com.google.android.inputmethod.latin: 2% user + 1.9% kernel / faults: 2093 minor 75 major
      0% 1021/media.codec: 0% user + 0% kernel / faults: 4659 minor 62 major
      2.9% 289/pp_event: 0% user + 2.9% kernel
      2.3% 883/audioserver: 1.9% user + 0.4% kernel / faults: 118 minor 4 major
      0% 2148/.qtidataservices: 0% user + 0% kernel / faults: 1158 minor 88 major
      2.2% 2255/com.android.phone: 1.4% user + 0.7% kernel / faults: 970 minor 110 major
      1.7% 3642/com.android.nfc: 0.8% user + 0.8% kernel / faults: 1177 minor 189 major
      0% 995/media.extractor: 0% user + 0% kernel / faults: 1958 minor 29 major
      1.3% 3604/com.google.android.googlequicksearchbox:interactor: 1% user + 0.2% kernel / faults: 878 minor 51 major
      0% 3761/com.qualcomm.qti.services.secureui:sui_service: 0% user + 0% kernel / faults: 1396 minor 245 major
      1.1% 835/android.hardware.audio@2.0-service: 0.4% user + 0.7% kernel
      1% 1133/adbd: 0.4% user + 0.5% kernel / faults: 1 minor
      0% 2092/.dataservices: 0% user + 0% kernel / faults: 995 minor 194 major
      1% 2202/com.google.android.grilservice: 0.5% user + 0.4% kernel / faults: 960 minor 132 major
      0% 3679/com.android.se: 0% user + 0% kernel / faults: 986 minor 208 major
      0% 3732/com.google.SSRestartDetector: 0% user + 0% kernel / faults: 956 minor 223 major
      0% 2120/com.google.android.cbrsnetworkmonitor: 0% user + 0% kernel / faults: 945 minor 208 major
      0% 2166/com.qualcomm.qti.telephonyservice: 0% user + 0% kernel / faults: 1007 minor 198 major
      0% 2233/com.android.networkstack.process: 0% user + 0% kernel / faults: 846 minor 61 major
      0% 3709/com.android.ims.rcsservice: 0% user + 0% kernel / faults: 966 minor 196 major
      0.7% 580/servicemanager: 0.4% user + 0.2% kernel
      0% 2181/com.android.refreshratecontrol: 0% user + 0% kernel / faults: 934 minor 201 major
      0.5% 1853/com.android.bluetooth: 0.1% user + 0.4% kernel / faults: 158 minor 13 major
      0.5% 7580/kworker/u16:1: 0% user + 0.5% kernel
      0.5% 13178/kworker/u16:4: 0% user + 0.5% kernel
      0.4% 9/rcu_preempt: 0% user + 0.4% kernel
      0.4% 271/kgsl_worker_thr: 0% user + 0.4% kernel
      0.4% 285/crtc_event:127: 0% user + 0.4% kernel
      0.4% 579/logd: 0.2% user + 0.1% kernel
      0.4% 857/android.hardware.sensors@2.0-service: 0.2% user + 0.1% kernel
      0.4% 20168/com.google.android.apps.maps: 0.4% user + 0% kernel / faults: 6 minor
      0.4% 20467/kworker/u17:1: 0% user + 0.4% kernel
      0.4% 21685/kworker/u16:8: 0% user + 0.4% kernel
      0.4% 21715/logcat: 0.2% user + 0.1% kernel
      0% 1050/tombstoned: 0% user + 0% kernel / faults: 31 minor 55 major
      0.2% 2614/com.google.android.gms.persistent: 0.1% user + 0.1% kernel / faults: 101 minor
      0.2% 3065/com.google.android.gms: 0.1% user + 0.1% kernel / faults: 68 minor 5 major
      0.2% 6253/kworker/u16:6: 0% user + 0.2% kernel
      0.2% 6428/com.zhiliaoapp.musically: 0.2% user + 0% kernel / faults: 2 minor
      0.1% 10/rcu_sched: 0% user + 0.1% kernel
      0.1% 12/rcuop/0: 0% user + 0.1% kernel
      0.1% 22/rcuop/1: 0% user + 0.1% ker
```

**Comment by Guardiola31337** [comment] 2020-02-26 14:19
It seems unrelated to https://github.com/mapbox/mapbox-events-android/pull/453 but [Mapbox-Android-Telemetry 4.7.2](https://github.com/mapbox/mapbox-events-android/releases/tag/telem-4.7.2-core-1.4.1) was recently released. We should check if we're able to reproduce OP with that version @kmadsen

**Comment by nkukday** [comment] 2020-06-05 19:13
https://github.com/mapbox/mapbox-gl-native-android/issues/126

**Comment by harvsu** [comment] 2020-06-09 18:17
Closing as duplicate of https://github.com/mapbox/mapbox-gl-native-android/issues/126 .

**Closed by harvsu** 2020-06-09 18:17 UTC
Labels: bug, duplicate
